import DashboardLayout from "./layout/dashboardLayout";

export const metadata = {
  title: "Dashobard ",
  description: "Generated by create next app",
};

export default function dashboardMainLayout({ children }) {
  return <DashboardLayout>{children}</DashboardLayout>;
}
